### ISSUE TITLE
Multiple chart in one page?

### ISSUE THREAD

**Issue by caccac** [airblade/chartjs-ror#15] opened 2015-06-25 14:40 UTC
I want to show multiple chart in one page, for example using this:

<%= chartjs_line_chart @data, @options %>
<%= chartjs_pie_chart @datastaffcount %>

but when its rendered it only show first chart and the other is blank.

Did you ever see a problem like this?

**Comment by airblade** [comment] 2015-06-25 17:14
That's odd.  I have three charts on one page in one of my projects.

Does it work if you specify an explicit `id` for each chart?

What error do you see in the browser's javascript console?

I'll be able to look into this more when I get back from holiday.

**Comment by caccac** [comment] 2015-06-25 20:36
thanks airblade for your help.

If i add two chart in same div tag it ok. its rendered. But when I add two chart under different divs, it isnt rendered.

Then i apply you suggestion and i specify an explicit id for each chart and ta taa.

Now two charts are rendered under different divs without any problem.

Again thanks for your help airblade.

**Comment by airblade** [comment] 2015-08-18 07:08
I'm glad it works when you specify an explicit id for each chart...but it should work without you having to do that.  I have a page in my app with three charts and it renders without my having to specify the ids.

What does the HTML generated look like when you don't specify ids?

**Comment by airblade** [comment] 2015-08-26 09:32
I can't reproduce this and it's gone quiet, so I'm closing this.  I'm happy to re-open it if you're still having problems.

**Closed by airblade** 2015-08-26 09:32 UTC
